<?xml version="1.0" encoding="UTF-8"?>
<Project DefaultTargets="Greeting" xmlns="http://schemas.microsoft.com/developer/msbuild/2003"><PropertyGroup><CorpusGreeting>Hello, World!</CorpusGreeting></PropertyGroup><Target Name="Greeting"><Message Text="$(CorpusGreeting)" Importance="high"/></Target></Project>
