const assert = require('node:assert/strict');
const fs = require('node:fs');
const {Preprocessor} = require('content-tag');
const {preprocess} = require('@glimmer/syntax');
const babel = require('@babel/core');
const filename = 'hello.gts';
const source = fs.readFileSync(__dirname+'/'+filename, 'utf8');
const compiler = new Preprocessor();
const parsed = compiler.parse(source, {filename});
assert.equal(parsed.length, 1);
const ast = preprocess(parsed[0].contents);
const heading = ast.body[0];
assert.equal(heading.type, 'ElementNode');
assert.equal(heading.tag, 'h1');
if (filename.endsWith('.gjs')) assert.equal(heading.children[0].chars, 'Hello, World!');
else assert.equal(heading.children[0].path.original, 'greeting');
const output = compiler.process(source, {filename});
assert.ok(output.code.includes('Hello, World!'));
const host = babel.transformSync(output.code, {filename:filename.replace('.gts','.ts'), configFile:false, babelrc:false, presets:[['@babel/preset-typescript',{ignoreExtensions:true}]]});
assert.ok(host.code);
console.log('content-tag native WASM/SWC, Glimmer template parser and Babel host syntax PASS.');
console.log('Ember component rendering remains pending.');
