local compiler = require("moonscript.base")
local file = assert(io.open(arg[1], "rb"))
local source = file:read("*a"); file:close()
local lua, err = compiler.to_lua(source)
assert(lua, err)
local output = assert(io.open(arg[2], "wb")); output:write(lua); output:close()
local program, load_error = load(lua, "@greeting_generated.lua")
assert(program, load_error)
program()
