TMPDIR = "${TOPDIR}/tmp"
CACHE = "${TMPDIR}/cache"
STAMP = "${TMPDIR}/stamps/${PN}"
T = "${TMPDIR}/work/${PN}/temp"
B = "${TMPDIR}/work/${PN}/build"
DL_DIR = "${TOPDIR}/downloads"
BB_NUMBER_THREADS = "1"
PN = "${@bb.parse.vars_from_file(d.getVar('FILE', False), d)[0]}"
