$MOD51
ORG 0000H
LJMP START
ORG 0030H
START: MOV TMOD,#20H
       MOV TH1,#0FDH
       MOV SCON,#50H
       SETB TR1
       MOV DPTR,#MESSAGE
SEND:  CLR A
       MOVC A,@A+DPTR
       JZ DONE
       MOV SBUF,A
WAIT:  JNB TI,WAIT
       CLR TI
       INC DPTR
       SJMP SEND
DONE:  SJMP DONE
MESSAGE: DB "Hello, World!",10,0
END
