DEFINE VARIABLE greetingWindow AS WIDGET-HANDLE NO-UNDO.
CREATE WINDOW greetingWindow ASSIGN TITLE = "Hello, World!" WIDTH-CHARS = 40 HEIGHT-CHARS = 5 VISIBLE = TRUE.
WAIT-FOR CLOSE OF greetingWindow.
DELETE WIDGET greetingWindow.
