<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:tns="urn:corpus:greeting" name="CorpusGreeting" targetNamespace="urn:corpus:greeting"><documentation>Hello, World!</documentation><message name="Greeting"><part name="message" type="xs:string"/></message><portType name="GreetingPortType"><operation name="hello"><output message="tns:Greeting"/></operation></portType></definitions>
