<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>Corpus Greeting</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>Hello, World!</string>
			<key>name</key>
			<string>string.other.greeting</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>text.corpus-greeting</string>
	<key>uuid</key>
	<string>4FBD8638-57BE-502F-9D97-1663684FE1E5</string>
</dict>
</plist>
